-- CREATE NEW DATABASE 
CREATE DATABASE pet_store;

-- SHOW ALL DATABASES 
SHOW DATABASES; 

-- USE THE DATABASE
USE pet_store;

-- SHOW CURRENT DATABASE
SELECT database();

-- DROP DATABES
DROP DATABASE PET_STORE;

-- CREATE TABLE
CREATE TABLE PET_TYPE(
	BREED VARCHAR(50),
    ORIGIN VARCHAR(50),
    LIFE_SPAN INT
);

--  SHOW TABLES IN THE DATABASE
SHOW TABLES;

-- SHOW COLUMNS /  TABLE INFORMATION
SHOW COLUMNS FROM PET_TYPE;

-- OR USE
DESC PET_TYPE;

-- DROP A TABLE
DROP TABLE CATS;