SHOW TABLES;

DESC PET_TYPE;

-- INSERTING DATA IN THE TABLE
INSERT INTO pet_type(BREED, ORIGIN, LIFE_SPAN) VALUES 
("POMARIAN", "USA", 14);

-- INSERTING MULTIPLE DATA IN THE TABLE
INSERT INTO pet_type(BREED, ORIGIN, LIFE_SPAN) 
VALUES ("PUG", "USA", 10),
	("LAB", "LONDON", 16),
    ("GERMAN SHEFARD", "GERMANY", 13),
    ("STREET", "INDIA", 11);


-- SHOWING ALL DATA IN THE TABLE
SELECT * FROM PET_TYPE;