CREATE TABLE PEOPLE(
	FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
	AGE INT 
);

DESC PEOPLE;

INSERT INTO PEOPLE(FIRST_NAME, LAST_NAME, AGE)
VALUES ("TINA", "BELCHER", 13);

INSERT INTO PEOPLE(FIRST_NAME, LAST_NAME, AGE)
VALUES ("PHILIP", "FROND", 38),
	("CALVIN", "FISHCODER", 70);

SELECT * FROM PEOPLE;