-- NOT NULL WILL PREVENT THE INSEART COMMAND WITHOUT VALUES
CREATE TABLE DOGS(
	NAME VARCHAR(20) NOT NULL,
	AGE INT 
);

DESC DOGS;

-- SHOWS ERROR =  Error Code: 1364. Field 'NAME' doesn't have a default value	0.000 sec
INSERT INTO DOGS( AGE) 
VALUES(20);