DESC DOGS;

INSERT INTO DOGS(NAME, AGE) 
VALUES("MILO",20);

SELECT * FROM DOGS;


-- TRY TO USE SINGLE QUOTES INSTEAD OF DOUBLE QUOTES
INSERT INTO DOGS(NAME, AGE) 
VALUES('MILO',12);


-- WE CAN USE / TO IGNORE THE QUOTATION INBETWEEN THE STERING
INSERT INTO DOGS(NAME, AGE) 
VALUES('LALA\'S DUTT', 12);

SELECT * FROM DOGS;
