CREATE TABLE CHICKEN(
	ID INT PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL default 'MILO',
	AGE INT 
);
DESC CHICKEN2;

--  OR WE CAN USE

-- imp: PRIMARY KEY VARIBALE WILL ALWAYS BE NOT NULL SO WE DONT HAVE TO SPECIFY IT 
CREATE TABLE CHICKEN2(
	ID INT NOT NULL,
	NAME VARCHAR(20) NOT NULL default 'MILO',
	AGE INT,
    PRIMARY KEY(ID)
);

DESC CHICKEN2;


-- AUTO_INCREMENT CAN BE USED TO AUTOMATICALLY INCREASE THE VALUES
CREATE TABLE CHICKEN3(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(20) NOT NULL default 'MILO',
	AGE INT,
    PRIMARY KEY(ID)
);

DESC CHICKEN3;

-- WE DONT HAVE TO ASSIGN THE ID BCOZ IT IS AUTO INCREMENT
INSERT INTO CHICKEN3 (NAME, AGE) VALUES ('BINGO', 2);
INSERT INTO CHICKEN3 (NAME, AGE) VALUES ('PAMA', 2);
INSERT INTO CHICKEN3 (NAME, AGE) VALUES ('BINGO', 2);
INSERT INTO CHICKEN3 (NAME, AGE) VALUES ('PAMA', 2);
INSERT INTO CHICKEN3 (NAME, AGE) VALUES ('BINGO', 2);
INSERT INTO CHICKEN3 (NAME, AGE) VALUES ('PAMA', 2);


SELECT * FROM CHICKEN3;