CREATE TABLE EMPLOYEES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    LAST_NAME VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    MIDDLE_NAME VARCHAR(50),
    AGE INT NOT NULL,
    CURRENT_STATUS VARCHAR(50) NOT NULL DEFAULT 'EMPLOYED'
);

DESC EMPLOYEES;

INSERT INTO EMPLOYEES (LAST_NAME, FIRST_NAME, MIDDLE_NAME, AGE)
VALUES ('TRIVEDI', 'MANOJ', 'JAYESHBHAI', 34);

SELECT * FROM EMPLOYEES;