SELECT * FROM CATS;

-- SELECTING SPECIFIC ENTRIES USING WHERE CLAUSE
SELECT NAME, AGE FROM CATS WHERE AGE>5;

-- WE CAN ALSO USE IT TO FIND THE MATCH 
-- FOR STRING WE DONT HAVE TO MAKE IT CASE SENSITIVE
SELECT NAME, AGE FROM CATS WHERE BREED = 'Maine Coon';


