SELECT * FROM CATS;

-- WE CAN USE AS - ALIAS TO USE INSTEAD OF THE COLUMN NAME
SELECT NAME AS CAT_NAME FROM CATS;
-- THIS DOESNT CHANGE THE ORIGINAL TABLE BUT IT PRINTS THE NEW TABLE WITH THE CHANGED COLUMN NAME