INSERT INTO EMPLOYEES (LAST_NAME, FIRST_NAME, MIDDLE_NAME, AGE)
VALUES ('DWIVWDI', 'NARAVANE', 'RAMESHBHAI', 34),
('CHAURVEDI', 'PALAK', 'SURESHBHAI', 32),
('PATHAK', 'MANAN', 'PARESHBHAI', 65),
('DAVE', 'DEV', 'PINKESHBHAI', 37);

SELECT * FROM EMPLOYEES;

-- WE CAN USE UPDATE COMMAND TO UPDATE THE SELECTED ROW USING WHERE AND USE SET COMMAND TO SET THE VALUES
UPDATE EMPLOYEES SET CURRENT_STATUS = 'UNEMPLOYED' WHERE ID = 5;
SELECT * FROM EMPLOYEES;

-- IF WE DONT USE THE WHERE THEN EVERY FIELD WILL BE UPDATED

-- WE CAN ALSO UPDATE MULTIPLE COLUMNS AT THE SAME TIME WITH SEPERATION OF COMMA
UPDATE EMPLOYEES SET CURRENT_STATUS = 'UNEMPLOYED', MIDDLE_NAME = 'NOT OF USE' WHERE ID = 5;
SELECT * FROM EMPLOYEES;