SELECT * FROM CATS;

--  THIS WILL DELETE ALL THE DATA FROM THE TABLE
DELETE FROM CATS;

-- WE USE WHERE TO DELETE SPECIFIC DATA FROM  THE TABLE
DELETE FROM CATS WHERE NAME = 'EGG';
SELECT * FROM CATS;

-- THIS WONT DELETE THE TABLE BUT IT WILL DELETE THE ENTRIES IN THE TABLE
SELECT * FROM EMPLOYEES;
DELETE FROM EMPLOYEES;
SELECT * FROM EMPLOYEES;
