-- CREATE DATABASE
CREATE DATABASE SHIRTS_DB;

-- USE DATABASE
USE SHIRTS_DB;

-- CREATE TABLE
CREATE TABLE shirts
  (
    shirt_id INT NOT NULL AUTO_INCREMENT,
    article VARCHAR(100),
    color VARCHAR(100),
    shirt_size VARCHAR(100),
    last_worn INT,
    PRIMARY KEY(shirt_id)
  );
  
  -- SHOW STRUCTURE OF THE TABLE
  DESC SHIRTS;
  
  -- INSERT DATA 
  INSERT INTO shirts (article, color, shirt_size, last_worn)  
VALUES 
	('t-shirt', 'white', 'S', 10),
	('t-shirt', 'green', 'S', 200),
	('polo shirt', 'black', 'M', 10),
	('tank top', 'blue', 'S', 50),
	('t-shirt', 'pink', 'S', 0),
	('polo shirt', 'red', 'M', 5),
	('tank top', 'white', 'S', 200),
	('tank top', 'blue', 'M', 15);

INSERT INTO shirts (article, color, shirt_size, last_worn)
VALUES ('polo shirt','purple', 'M', 50);

SELECT * FROM SHIRTS;

-- ONLY PRINT ARTICLE AND COLOR
SELECT ARTICLE, COLOR FROM SHIRTS;

-- SELECT ALL MEDIUM SHIRTS PRINT EVERYTHING EXCEPT SHIRTID
SELECT ARTICLE,COLOR,SHIRT_SIZE,LAST_WORN FROM SHIRTS WHERE SHIRT_SIZE = 'M';

-- UPDATE ALL POLO SHIRT TO SIZE = 12
UPDATE SHIRTS SET SHIRT_SIZE = 12 WHERE ARTICLE = 'POLO SHIRT';
SELECT * FROM SHIRTS;

-- UPDATE THE SHIRT WITH LAST_WORN = 15 TO LAST_WORN = 0
UPDATE SHIRTS SET LAST_WORN = 0 WHERE LAST_WORN = 15;
SELECT * FROM SHIRTS;

-- UPDATE ALL WHITE SHIRTS WHER SIZE=XS AND COLOR = OFF WHITE
UPDATE SHIRTS SET SHIRT_SIZE = 'XS', COLOR = 'OFF WHITE' WHERE COLOR = 'WHITE';
SELECT * FROM SHIRTS;

-- DELETE ALL SHIRTS THAT ARE LAST WORN 200 DAYS AGO
DELETE FROM SHIRTS WHERE LAST_WORN >= 200;
SELECT * FROM SHIRTS;

-- DELETE ALL TANK TOPS
DELETE FROM SHIRTS WHERE ARTICLE = 'TANK TOP';
SELECT * FROM SHIRTS;

-- DELETE ALL SHIRTS
DELETE FROM SHIRTS;
SELECT * FROM SHIRTS;


-- DELETE TABLE
DROP TABLE SHIRTS;
SHOW TABLES;
