-- REVERSE AND UPPERCASE USING A SINGLE QUERY
SELECT REVERSE(UPPER('Why does my cat look at me with such hatred?'));

-- SHOW OUTPUT
SELECT 
    REPLACE(CONCAT('I', ' ', 'LIKE', ' ', 'CATS'),
        ' ',
        '-');

SELECT * FROM BOOKS;
-- REPLACE ' ' IN TITLE WITH '-'
SELECT 
    REPLACE(TITLE, ' ', '->') AS TITLE
FROM
    BOOKS;

-- PRINT THE AUTHOR_FNAME AND ADD A COLUMN WITH IT REVERSE
SELECT 
    AUTHOR_FNAME AS FORWARD, REVERSE(AUTHOR_FNAME) AS REVERSE
FROM
    BOOKS;

-- PRINT FULLNAME OF AUTHOR IN CAPS
SELECT 
    CONCAT(UPPER(AUTHOR_FNAME),
            ' ',
            UPPER(AUTHOR_LNAME)) AS FULLNAME
FROM
    BOOKS;

-- GENERATING BLURB
-- THE 'TITLE' WAS RELEASED IN 'YEAR'
SELECT 
    CONCAT('THE',
            TITLE,
            ' WAS RELEASED IN ',
            RELEASED_YEAR) AS BLURB
FROM
    BOOKS;

-- PRINT VOOK TITLES AND RHE LENGTH
SELECT 
    TITLE, CHAR_LENGTH(TITLE) AS CHARACTER_COUNT
FROM
    BOOKS;


SELECT * FROM BOOKS;
-- PRINT IN THIS FORMAT
-- SHORT_TITLE AUTHOR QUANTITY
-- SHORT_TITLE = FIRST 10 LETTER + '...'
-- AUTHOR = AUTHOR_FNAME + '-' + AHTHOR_LANME
-- QUANTITY = STOCK_QUANTITY + 'IN STOCKS'
SELECT 
    CONCAT(SUBSTR(TITLE, 1, 10), '...') AS SHORT_TITLE,
    CONCAT(AUTHOR_LNAME, ',', AUTHOR_FNAME) AS AUTHOR,
    CONCAT(STOCK_QUANTITY, ' IN STOCKS') AS QUANTITY
FROM
    BOOKS; 