-- THIS IS USED AFTER ORDER BY

SELECT 
    BOOK_ID, TITLE, RELEASED_YEAR
FROM
    BOOKS;

-- LIMIT KEYWORD IS USED TO LIMIT THE RESULT
SELECT 
    BOOK_ID, TITLE, RELEASED_YEAR
FROM
    BOOKS
LIMIT 5;


-- GET THE EARLIST 5 RELEASED BOOKS
SELECT 
    BOOK_ID, TITLE, RELEASED_YEAR
FROM
    BOOKS
ORDER BY RELEASED_YEAR
LIMIT 5;


-- GET THE LATEST 5 RELEASED BOOKS
SELECT 
    BOOK_ID, TITLE, RELEASED_YEAR
FROM
    BOOKS
ORDER BY RELEASED_YEAR DESC
LIMIT 5;

-- WE CAN PASSS TWO VALUES TO LIMIT
-- LIMIT STARTING AND SIZE
SELECT 
    BOOK_ID, TITLE, RELEASED_YEAR
FROM
    BOOKS
ORDER BY RELEASED_YEAR DESC;

-- NEXT 5 BOOKS
SELECT 
    BOOK_ID, TITLE, RELEASED_YEAR
FROM
    BOOKS
ORDER BY RELEASED_YEAR DESC
LIMIT 5 , 5;

-- IF WE EXCEED THE SIZE OF TEH TABLE THEN IT WONT SHOW ERROR AND GIVE US THE WHOLE TABLE AS OUTPUT
