SELECT 
    *
FROM
    BOOKS;

-- TITLE WITH THE WORD STORIES IN IT
SELECT 
    TITLE
FROM
    BOOKS
WHERE
    TITLE LIKE '%STORIES%';

-- FIND THE LONGEST BOOKS AND PRINT TITLE AND PAGE COUNT
SELECT 
    TITLE, PAGES
FROM
    BOOKS
ORDER BY PAGES DESC
LIMIT 1;

-- PRINT TITLE AND YEAR OF THREE MOST RECENT BOOKS
SELECT 
    CONCAT_WS(' - ', TITLE, RELEASED_YEAR) AS SUMMARY
FROM
    BOOKS
ORDER BY RELEASED_YEAR DESC
LIMIT 3;

-- FIND ALL BOOKS WITH AUTHOR_LNAME CONSTANS ' ' - SPACE
SELECT 
    TITLE, AUTHOR_LNAME
FROM
    BOOKS
WHERE
    AUTHOR_LNAME LIKE '% %';

-- 3 BOOKS WITH LOWEST STOCK QUANTITY
SELECT 
    TITLE, RELEASED_YEAR, STOCK_QUANTITY
FROM
    BOOKS
ORDER BY STOCK_QUANTITY , RELEASED_YEAR DESC
LIMIT 3;

-- PRINT TITLE AND AUTHOR_LNAME SORTED FIRST BY AUTHOR_NAME AND THEN BY TITLE
SELECT 
    TITLE, AUTHOR_LNAME
FROM
    BOOKS
ORDER BY AUTHOR_LNAME , TITLE; 

-- PRINT 'MY FAVOURITE AUTHOR IS 'AUTHOR NAME''
SELECT 
    CONCAT('MY FAVOURTITE AUTHOR NAME IS ',
            UPPER(AUTHOR_FNAME),
            ' ',
            UPPER(AUTHOR_LNAME)) AS YELL
FROM
    BOOKS
ORDER BY AUTHOR_LNAME;