-- AGGRIGATE FUNCTIONS

-- COUNT FUNCTION -  COUNT THE NUMBER OF ENTRIES
SELECT COUNT(*) FROM books; -- 19

-- THIS FUNCTION SHOULD BE USED INDEPENDENTLY BCOZ IT ONLY RETURN ONE ROW

-- ID DOES NOT COUNT NULL VALUES

SELECT * FROM books;
INSERT INTO books () VALUES ();

SELECT COUNT(*) FROM books; 
SELECT COUNT(AUTHOR_FNAME) FROM books;

-- COUNT THE DISTINCT FNAMES
SELECT COUNT(DISTINCT AUTHOR_FNAME) FROM books; -- 12 	 


-- HOW MANY TITLES CONTAINS 'THE'
SELECT COUNT(*) FROM books WHERE TITLE LIKE '%THE%';