SELECT * FROM books;

-- FIND THE EARLIST YEAR THE BOOK WAS RELEASED
SELECT MIN(RELEASED_YEAR) FROM books;


-- FIND THE MAXIMUM PAGES THAT A BOOK HAVE
SELECT MAX(PAGES) FROM books;


-- FIND THE TITLE OF THE LONGEST BOOK
-- SELECT TITLE, MAX(PAGES) FROM books;
-- THIS GIVES ERROR BOZ MIN AND MAX ARE AGGRIGATING FUNCTIONS AND WE CANNOT USE IT TO DISPLAY OTHER FIELDS

-- OTHER OPTION
SELECT TITLE, PAGES FROM books ORDER BY PAGES DESC LIMIT 1; 