-- SUM() - FIND THE SUM OF ALL THE FIELDS

-- FIND THE SUM OF ALL PAGES EACH AUTHOR HAS WRITTEN
SELECT CONCAT(AUTHOR_FNAME, ' ', AUTHOR_LNAME) AS NAME, SUM(PAGES) AS TOTAL_PAGES
FROM books
GROUP BY NAME
ORDER BY 2 DESC;