CREATE DATABASE practice;

USE practice;


CREATE TABLE chardata(
	NAME VARCHAR(20),
	CODE CHAR(4)
)

-- CHAR STORES FIXED SIZED DATA MEANS IT WILL PAD REMAINING BIT WITH THE SPACE ADN AGAIN DISPLAY IT WITHOUT SPACE
INSERT INTO chardata(NAME, CODE ) VALUES('pudman', '12');
-- VARCHAR IS PREFERED WHEN WE HAVE VARIABLE SIZED DATA

SELECT LENGTH(NAME), LENGTH(CODE) FROM chardata;