-- NUMERIC DATATYES ARE USED ACCORDING TO SIZE REQUIREMENTS
-- TINYINT
-- SMALLINT
-- MEDIUMINT
-- INT 
-- BIGINT

-- THERE ARE SIGNED AND UNSIGNED VALUES

-- DECIMAL(NO. OF DIGITS, NO OF DECIMAL ACCURACY)

CREATE TABLE MARKS(
	TOTAL DECIMAL(4,2)
);
-- THIS MEANS THAT 4 DIGIT WITH 2 DECIMAL PLACES -->     XX.XX

CREATE TABLE MARKS2(
	TOTAL FLOAT,
	FIANL DOUBLE
);
-- DOUBLE HAS TWICE THE SIZE OF FLOAT