-- DATE MATH

-- DATEDIFF(DATE1, DATE2) - IT RETURNS THE NUMBER OF DAYS
SELECT DATEDIFF('2000-12-12','2002-12-12');

-- FINDING HOW MANY DAYS FROM NOW THE BIRTHDATE WAS
SELECT BIRTHDATE, DATEDIFF(CURDATE(), BIRTHDATE)
FROM datetimetable;

-- ----------------------------------------------------------

-- DATE_ADD() AND DATE_SUB() ARE FUNCTIONS TO ADD AND SUB DATES

-- INTERVAL

-- INTERVAL IS USED TO SPECIFY THE RELATIVE TIME IN TERMS OF INTERVAL
SELECT BIRTHDATE, DATE_ADD(BIRTHDATE, INTERVAL 18 YEAR)
FROM datetimetable;

-- -----------------------------------------------------------
 
