-- The TIMESTAMP data type is used for values that contain both date and time parts. 
-- TIMESTAMP has a range of ' 1970-01-01 UTCto '2038-01-19 03:14:07' UTC.
-- TIMSTAMP USES LESS STORAGE SIZE AS COMPARED TO DATETIME

-- WE HAVE FUNCTIONS LIKE TIMESTAMPADD() ADN TIMESTAMPDIFF()

-- THIS WILL BY DEFAULT TAKE CURRENT TIMESTAMP
CREATE TABLE CAPTIONS(
	TEXT VARCHAR(20),
	TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DESC CAPTIONS;

INSERT INTO CAPTIONS(TEXT) VALUES('ABC');

SELECT * FROM CAPTIONS;


-- THIS WILL BE UPDATED ON EVERY CHANGE
CREATE TABLE CAPTIONS2(
	TEXT VARCHAR(20),
	US TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP	
);

INSERT INTO CAPTIONS2(TEXT) VALUES('ABC');


SELECT * FROM CAPTIONS2;

UPDATE CAPTIONS2 SET TEXT='mno';