-- COMPARISION OPERATORS
USE BOOK_STORE;

-- NOT OPERATOR
SELECT * FROM BOOKS;

-- SELECT ALL BOOKS EXCEPT GAIMIN BOOKS
SELECT TITLE, AUTHOR_FNAME FROM BOOKS WHERE AUTHOR_LNAME != 'GAIMAN';


-- SELECT BOOKS WHICH HAS NO SPACE IN THE TITLE
SELECT TITLE FROM BOOKS WHERE TITLE NOT LIKE '% %';

-- ALL THE BOOK TITLE THAT DOWS NOT HAVE LETTER 'E'
SELECT TITLE FROM BOOKS WHERE TITLE NOT LIKE '%E%';

-- -------------------------------------------------------------------

-- GREATER THAN AND LESS THEN

SELECT (99>1); -- RETURNS 1 
SELECT (1>99); -- RETURNS 0
-- 1 MEANS TRUE AND 0 MEANS FASLE