-- LOGICAL OPERATORS

-- AND OPERATION
-- SELECT BOOKS THAT ARE WRITTEN BY AUTHOR 'EGGERS' AND RELEASED AFTER 2010
SELECT TITLE,AUTHOR_LNAME,RELEASED_YEAR
FROM BOOKS
WHERE AUTHOR_LNAME = 'EGGERS' AND RELEASED_YEAR>2010;


-- OR OPERATION
SELECT TITLE,AUTHOR_LNAME,RELEASED_YEAR
FROM BOOKS
WHERE AUTHOR_LNAME = 'EGGERS' OR RELEASED_YEAR>2010;


-- SELECT ALL BOOKS THAT HAVE PAGE NUMBER < 200 OR HAVE 'STORIES' WRITTEN IN THE TITLE
SELECT TITLE, PAGES FROM BOOKS WHERE PAGES<200 OR TITLE LIKE '%STORIES%'