-- IN OPERATOR
USE BOOK_STORE;

-- FIND IF AUTHOR_LNAME IS EQUAL TO 'CARVER' OR 'LAHIRI' OR 'SMITH'
SELECT TITLE,AUTHOR_LNAME
FROM BOOKS
WHERE AUTHOR_LNAME = 'CARVER' OR AUTHOR_LNAME = 'LAHIRI' OR AUTHOR_LNAME = 'SMITH';

SELECT TITLE, AUTHOR_LNAME
FROM BOOKS
WHERE AUTHOR_LNAME IN ('CARVER', 'LAHIRI', 'SMITH' );


-- NOT IN OPERATOR
SELECT TITLE, AUTHOR_LNAME
FROM BOOKS
WHERE AUTHOR_LNAME NOT IN ('CARVER', 'LAHIRI', 'SMITH' );