SELECT * FROM books;

-- SELECT ALL BOOKS WRITTEN BEFORE 1980
SELECT TITLE, RELEASED_YEAR FROM books WHERE RELEASED_YEAR < 1980;

-- ALL BOOKS WRITTEN BY AUTHOR 'EGGER' OR 'CHABON'
SELECT TITLE, AUTHOR_LNAME FROM books WHERE AUTHOR_LNAME = 'EGGERS' OR AUTHOR_LNAME = 'CHABON';

-- ALL BOOKS WRITTEN BY LAHIRI PUBLISHED AFTER 2000
SELECT TITLE, AUTHOR_LNAME, RELEASED_YEAR FROM books WHERE AUTHOR_LNAME = 'LAHIRI' AND RELEASED_YEAR > 2000;

-- SELECT ALL BOOKS WITH PAGE COUNT BETWEEN 100 AND 200
SELECT TITLE, PAGES FROM books WHERE PAGES BETWEEN 100 AND 200;

-- SELECT ALL BOOKS WHERE AUTHOR_LNAME STARTS WITH 'C' OR 'S'
SELECT TITLE, AUTHOR_LNAME FROM books WHERE AUTHOR_LNAME LIKE 'C%' OR AUTHOR_LNAME LIKE 'S%';


SELECT TITLE, AUTHOR_LNAME,
	CASE 
	WHEN TITLE LIKE '%STORIES%' THEN 'SHORT STORIES'
	WHEN TITLE = 'Just Kids' OR TITLE = 'A Heartbreaking Work of Staggering Genius' THEN 'MEMOIR'
	ELSE 'NOVEL'
END AS TYPE
FROM books;


SELECT AUTHOR_FNAME, AUTHOR_LNAME, CASE WHEN  COUNT(*)=1 THEN '1 BOOK'
ELSE  CONCAT(COUNT(*), ' BOOKS')
END  AS COUNT
FROM books GROUP BY AUTHOR_LNAME, AUTHOR_FNAME;


