SHOW TABLES;

DESC COMPANIES;

-- ------------------------------------------------------------

-- ADD COLUMN IS USED TO ADD A COLUMN
-- IT IS PREFERRED TO ADD A DEFAULT VALUE TO THE COLUMN IN ADDITION OF COLUMN 
ALTER TABLE COMPANIES
	ADD COLUMN EMAIL VARCHAR(50) NOT NULL DEFAULT 1;
	
DESC COMPANIES;

-- ------------------------------------------------------------

-- DROP COLUMN IS USED TO DROP A COLUMN
ALTER TABLE COMPANIES
	DROP COLUMN EMAIL;
	
DESC COMPANIES;

-- ------------------------------------------------------------

-- RENAME A TABLE
-- RENAME TABLE OLDNAME TO NEWNAME
RENAME TABLE COMPANIES TO NEW_COMPANIES;

SHOW TABLES;

-- ANOTHER SYNTAX
ALTER TABLE NEW_COMPANIES RENAME TO COMPANIES;

SHOW TABLES;

-- ------------------------------------------------------------

-- RENAME A COLUMN
-- ALTER TABLE COMPANIES RENAME COLUMN OLDNAME TO NEWNAME;
DESC COMPANIES;

ALTER TABLE COMPANIES RENAME COLUMN EMAIL TO MAIL;

DESC COMPANIES;

-- ------------------------------------------------------------

-- MODIFY THE COLUMN CONSTRAINTS OR DATATYPE
-- ALTER TABLE suppliers MODIFY COLUMN VARCHAR(100) ;

ALTER TABLE COMPANIES 
MODIFY COLUMN PHONE VARCHAR(10);

DESC COMPANIES;

-- -------------------------------------------------------------

-- ALTER CONSTRAINTS

-- ALTER TABLE TABLENAME ADD CONSTRAINT CONSTRAINT_NAME CHECK(ABC > 0)

ALTER TABLE COMPANIES ADD CONSTRAINT CHECK_PHONE CHECK(LENGTH(PHONE) = 10);

ALTER TABLE COMPANIES DROP CONSTRAINT CHECK_PHONE;

DESC COMPANIES;
