-- PRACTICE

USE SHOPPING;

DROP TABLE STUDENTS;
DROP TABLE PAPERS;


CREATE TABLE STUDENTS(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
	FIRST_NAME VARCHAR(20)
);

CREATE TABLE PAPERS(
	TITLE VARCHAR(50),
	GRADE INT,
	STUDENT_ID INT,
	FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(ID) ON DELETE CASCADE
);

DESC STUDENTS;
DESC PAPERS;


INSERT INTO students (first_name) VALUES 
('Caleb'), ('Samantha'), ('Raj'), ('Carlos'), ('Lisa');

INSERT INTO papers (student_id, title, grade ) VALUES
(1, 'My First Book Report', 60),
(1, 'My Second Book Report', 75),
(2, 'Russian Lit Through The Ages', 94),
(2, 'De Montaigne and The Art of The Essay', 98),
(4, 'Borges and Magical Realism', 89);


SELECT * FROM STUDENTS;
SELECT * FROM PAPERS;


SELECT FIRST_NAME, TITLE, GRADE FROM STUDENTS
JOIN PAPERS ON PAPERS.STUDENT_ID = STUDENTS.ID;


-- there is a function named ISNULL()

-- THIS FUNCTION TAKES INPUT OF 
-- IFNULL(FIRST, SECOND);
-- IF FIRST IS NULL THEN SECOND

SELECT FIRST_NAME, IFNULL(AVG(GRADE), 0) FROM students
LEFT JOIN PAPERS ON PAPERS.STUDENT_ID = STUDENTS.ID
GROUP BY FIRST_NAME;


SELECT FIRST_NAME, IFNULL(AVG(GRADE), 0) FROM students
LEFT JOIN PAPERS ON PAPERS.STUDENT_ID = STUDENTS.ID
GROUP BY FIRST_NAME
ORDER BY 2 DESC; 

SELECT FIRST_NAME, IFNULL(AVG(GRADE), 0), 
	CASE
		WHEN IFNULL(AVG(GRADE),0) > 75 THEN 'PASSING'
		ELSE 'FAIL'
	END AS RESULTS
FROM students
LEFT JOIN PAPERS ON PAPERS.STUDENT_ID = STUDENTS.ID
GROUP BY FIRST_NAME
ORDER BY 2 DESC;
